spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrPing666/config-repo.git
#          username:
#          password:
          search-paths: repo
          basedir: config-server/target/config
